"""
FootballAI Career Agent - 工具聚合模块
"""

from tools.calculator import CALCULATOR_TOOLS
from tools.database import DATABASE_TOOLS
from tools.search import SEARCH_TOOLS
from tools.rag import RAG_TOOLS

# 所有工具的集合
ALL_TOOLS = CALCULATOR_TOOLS + DATABASE_TOOLS + SEARCH_TOOLS + RAG_TOOLS

# 按 Agent 分组的工具
MANAGER_TOOLS = DATABASE_TOOLS + SEARCH_TOOLS
NUTRITION_TOOLS = CALCULATOR_TOOLS + DATABASE_TOOLS
COACH_TOOLS = RAG_TOOLS + DATABASE_TOOLS + SEARCH_TOOLS
ANALYST_TOOLS = DATABASE_TOOLS
CAREER_TOOLS = DATABASE_TOOLS + SEARCH_TOOLS
